name: 'Autoversion'
description: 'Automatically calculates the next patch version from a base and existing git tags'
author: 'Kevin Galligan'

inputs:
  versionBase:
    description: 'Base version value. Must be x.y.'
    required: true

outputs:
  nextVersion:
    description: 'Next version'

runs:
  using: node16
  main: dist/index.js
