name: 'Auto-version: Tag Marker'
description: 'Adds marker tags for pending versions, and cleans them up on a successful build.'
author: 'Kevin Galligan'

inputs:
  nextVersion:
    description: 'The next version to be built. Must be a valid semver string x.y.z'
    required: true

  cleanupMarkers:
    description: 'When build is successful, pass in true to clean up marker tags.'
    required: false

runs:
  using: node16
  main: dist/index.js
